### PR TITLE
update VSmu SFs for UL

### PR DESCRIPTION
**Pull request by YWen-AI**
As the title said

### CODE REVIEW

**Comment by IzaakWN** [comment]
Hey Yiwen, thanks! Can you just add back the pre-UL SFs in the dictionary, please? You can comment it out if you wish, it's just for future reference, I prefer to keep it.

**Comment by YWen-AI** [comment]
@IzaakWN DONE

**Comment by IzaakWN** [comment]
Looks good! Merging...

**Comment by IzaakWN** [comment]
Sorry, forgot to mention this earlier: As discussed in https://github.com/cms-tau-pog/TauFW/pull/9, the script for VSmu JSONs should be maintained in the `TauFW`, rather than here. The scripts in this repo were more meant for developing and validating the JSON format & scripts.

**Pull request merged**
